// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpjN8zUDeRpVJ2BHOk09s7bCDXxennPc0',
    appId: '1:178610942641:web:330318fa91396ba8f1a890',
    messagingSenderId: '178610942641',
    projectId: 'kejahunt-b5402',
    authDomain: 'kejahunt-b5402.firebaseapp.com',
    storageBucket: 'kejahunt-b5402.firebasestorage.app',
    measurementId: 'G-YP9LR93C19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBivdxE36iRtj0iaYq3UixFN_6tZxtiVqM',
    appId: '1:178610942641:android:115df8a0785e1830f1a890',
    messagingSenderId: '178610942641',
    projectId: 'kejahunt-b5402',
    storageBucket: 'kejahunt-b5402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtctb7ajcVdRAv_IynojES1XB4x8xbiFY',
    appId: '1:178610942641:ios:3801a60a95ad61bcf1a890',
    messagingSenderId: '178610942641',
    projectId: 'kejahunt-b5402',
    storageBucket: 'kejahunt-b5402.firebasestorage.app',
    iosBundleId: 'com.kenstarry.kejaHunt',
  );
}
